import 'app_language.dart';
import 'str_key.dart';

/// Translated UI strings. English is the source of truth; any key missing in
/// another language falls back to English so nothing ever renders blank.
///
/// Placeholders use `{name}` and are filled via [tr]'s `params`.
abstract final class AppStrings {
  static String tr(
    AppLanguage lang,
    StrKey key, [
    Map<String, Object>? params,
  ]) {
    final table = _all[lang] ?? _en;
    var text = table[key] ?? _en[key] ?? key.name;
    if (params != null) {
      params.forEach((k, v) => text = text.replaceAll('{$k}', '$v'));
    }
    return text;
  }

  static const Map<AppLanguage, Map<StrKey, String>> _all = {
    AppLanguage.english: _en,
    AppLanguage.german: _de,
    AppLanguage.swedish: _sv,
    AppLanguage.finnish: _fi,
  };

  static const Map<StrKey, String> _en = {
    StrKey.back: 'Back',
    StrKey.home: 'Home',
    StrKey.continueLevel: 'Continue • Level {n}',
    StrKey.levelSelect: 'Level Select',
    StrKey.twoPlayer: 'Two Player',
    StrKey.dailyChallenge: 'Daily Challenge',
    StrKey.levelsProgress: '{done} / {total} levels',
    StrKey.freeCoins: 'Free {n} coins',
    StrKey.loadingAd: 'Loading ad…',
    StrKey.greatJob: 'Great Job!',
    StrKey.outOfChances: 'Out of chances!',
    StrKey.lossEncourage: "Don't worry — every guess makes you sharper.",
    StrKey.theAnswerWas: 'The answer was',
    StrKey.statCoins: 'Coins',
    StrKey.statAccuracy: 'Accuracy',
    StrKey.statMistakes: 'Mistakes',
    StrKey.statStreak: 'Streak',
    StrKey.statDailyStreak: 'Daily streak',
    StrKey.rewardChest: 'Reward chest',
    StrKey.openChest: 'Open the chest!',
    StrKey.chestReward: '+{n} from the chest!',
    StrKey.replay: 'Replay',
    StrKey.next: 'Next',
    StrKey.tryAgain: 'Try Again',
    StrKey.newRound: 'New Round',
    StrKey.backToHome: 'Back to Home',
    StrKey.levelTitle: 'Level {n}',
    StrKey.dailyTitle: 'Daily Challenge',
    StrKey.playerTwoTurn: "Player 2's turn",
    StrKey.hintReveal: 'Reveal',
    StrKey.hintClear: 'Clear {n}',
    StrKey.hintPlusLife: '+1 Life',
    StrKey.notEnoughCoins: 'Not enough coins for that hint.',
    StrKey.noLettersHint: 'No letters left for that hint.',
    StrKey.alreadyExtra: 'You already used an extra chance here.',
    StrKey.revealWatchAd: 'Reveal a letter — watch ad',
    StrKey.reviveTitle: 'Out of chances!',
    StrKey.reviveMessage:
        'Watch a short ad to get {n} more guesses and keep '
        'this level going?',
    StrKey.watchAd: 'Watch ad',
    StrKey.noThanks: 'No thanks',
    StrKey.leaveTitle: 'Leave this level?',
    StrKey.leaveMessage: 'Your progress on this word will be lost.',
    StrKey.leave: 'Leave',
    StrKey.stay: 'Stay',
    StrKey.noAdAvailable: 'No ad available right now.',
    StrKey.buyExtraTitle: 'Buy an extra chance?',
    StrKey.buyExtraMessage:
        'Spend {n} coins to add one more allowed mistake for this level.',
    StrKey.buy: 'Buy',
    StrKey.encStart: "Let's crack this word!",
    StrKey.encWon: 'Brilliant work!',
    StrKey.encLost: "So close — let's try again.",
    StrKey.encAlmost: 'Almost there!',
    StrKey.encNice: 'Nice choice!',
    StrKey.encTryAnother: 'Try a different letter.',
    StrKey.settingsTitle: 'Settings',
    StrKey.settingSound: 'Sound effects',
    StrKey.settingMusic: 'Background music',
    StrKey.settingVibration: 'Vibration',
    StrKey.replayTutorial: 'Replay Tutorial',
    StrKey.privacyPolicy: 'Privacy Policy',
    StrKey.termsOfUse: 'Terms of Use',
    StrKey.privacyChoices: 'Privacy Choices',
    StrKey.resetProgress: 'Reset Progress',
    StrKey.settingLanguage: 'Language',
    StrKey.resetTitle1: 'Reset all progress?',
    StrKey.resetMsg1:
        'This clears levels, stars, coins, streaks and the daily challenge.',
    StrKey.resetContinueLabel: 'Continue',
    StrKey.resetTitle2: 'Are you absolutely sure?',
    StrKey.resetMsg2: 'This cannot be undone. Start completely fresh?',
    StrKey.resetConfirmLabel: 'Reset everything',
    StrKey.resetDone: 'Progress reset. Fresh start!',
    StrKey.skip: 'Skip',
    StrKey.startPlaying: 'Start Playing',
    StrKey.tut1Title: 'Read the clue',
    StrKey.tut1Body:
        'Each round shows a question or hint. It tells you what word to find.',
    StrKey.tut2Title: 'Pick letters',
    StrKey.tut2Body:
        'Tap letters to guess. Correct letters turn green and fill the blanks.',
    StrKey.tut3Title: 'Mind your mistakes',
    StrKey.tut3Body:
        'Wrong letters cost a chance and nudge our doodle friend into a silly '
        'spot. Run out and the round ends.',
    StrKey.tut4Title: 'Use hints & coins',
    StrKey.tut4Body:
        'Stuck? Spend coins on hints to reveal a letter, clear wrong ones, or '
        'earn an extra chance.',
    StrKey.tutDemoClue: 'Which animal builds dams?',
    StrKey.twoPlayerTitle: 'Two Player',
    StrKey.playerOne: 'Player 1',
    StrKey.secretPrompt:
        'Tap a box and type a secret word for Player 2 to guess.',
    StrKey.secretWordLabel: 'Secret word',
    StrKey.clueOptionalLabel: 'Clue (optional)',
    StrKey.secretHint: 'e.g. RAINBOW',
    StrKey.clueHint: 'Give a friendly hint',
    StrKey.allowedMistakes: 'Allowed mistakes: {n}',
    StrKey.passToPlayer2: 'Pass to Player 2',
    StrKey.showWord: 'Show word',
    StrKey.hideWord: 'Hide word',
    StrKey.valEmpty: 'Please enter a secret word.',
    StrKey.valChars: 'Use letters, spaces and hyphens only.',
    StrKey.valNeedsLetter: 'The word needs at least one letter.',
    StrKey.valMinLen: 'Make it at least {n} letters.',
    StrKey.valMaxLen: 'Keep it under {n} letters.',
    StrKey.twoPlayerClue: "Guess Player 1's secret word!",
    StrKey.twoPlayerCategory: 'Two Player',
    StrKey.levelSelectTitle: 'Level Select',
    StrKey.invalidTitle: 'That page ran off the paper',
    StrKey.invalidBody:
        "This level isn't available yet. Let's head back and pick another.",
    StrKey.backToLevels: 'Back to Levels',
    StrKey.chooseLanguage: 'Choose your language',
    StrKey.chooseLanguageSub: 'Menus and puzzles will be in this language.',
    StrKey.changeLanguageAnytime: 'You can change it later in Settings.',
  };

  static const Map<StrKey, String> _de = {
    StrKey.back: 'Zurück',
    StrKey.home: 'Start',
    StrKey.continueLevel: 'Weiter • Level {n}',
    StrKey.levelSelect: 'Levelauswahl',
    StrKey.twoPlayer: 'Zwei Spieler',
    StrKey.dailyChallenge: 'Tägliche Aufgabe',
    StrKey.levelsProgress: '{done} / {total} Level',
    StrKey.freeCoins: 'Gratis {n} Münzen',
    StrKey.loadingAd: 'Werbung lädt…',
    StrKey.greatJob: 'Super gemacht!',
    StrKey.outOfChances: 'Keine Versuche mehr!',
    StrKey.lossEncourage: 'Kein Problem – jeder Versuch macht dich besser.',
    StrKey.theAnswerWas: 'Die Antwort war',
    StrKey.statCoins: 'Münzen',
    StrKey.statAccuracy: 'Genauigkeit',
    StrKey.statMistakes: 'Fehler',
    StrKey.statStreak: 'Serie',
    StrKey.statDailyStreak: 'Tagesserie',
    StrKey.rewardChest: 'Schatztruhe',
    StrKey.openChest: 'Truhe öffnen!',
    StrKey.chestReward: '+{n} aus der Truhe!',
    StrKey.replay: 'Nochmal',
    StrKey.next: 'Weiter',
    StrKey.tryAgain: 'Erneut',
    StrKey.newRound: 'Neue Runde',
    StrKey.backToHome: 'Zum Start',
    StrKey.levelTitle: 'Level {n}',
    StrKey.dailyTitle: 'Tägliche Aufgabe',
    StrKey.playerTwoTurn: 'Spieler 2 ist dran',
    StrKey.hintReveal: 'Aufdecken',
    StrKey.hintClear: '{n} weg',
    StrKey.hintPlusLife: '+1 Leben',
    StrKey.notEnoughCoins: 'Nicht genug Münzen für diesen Tipp.',
    StrKey.noLettersHint: 'Keine Buchstaben mehr für diesen Tipp.',
    StrKey.alreadyExtra: 'Du hast hier schon einen Extra-Versuch genutzt.',
    StrKey.revealWatchAd: 'Buchstaben aufdecken – Werbung ansehen',
    StrKey.reviveTitle: 'Keine Versuche mehr!',
    StrKey.reviveMessage:
        'Kurze Werbung ansehen für {n} weitere Versuche in diesem Level?',
    StrKey.watchAd: 'Werbung ansehen',
    StrKey.noThanks: 'Nein danke',
    StrKey.leaveTitle: 'Level verlassen?',
    StrKey.leaveMessage: 'Dein Fortschritt bei diesem Wort geht verloren.',
    StrKey.leave: 'Verlassen',
    StrKey.stay: 'Bleiben',
    StrKey.noAdAvailable: 'Gerade keine Werbung verfügbar.',
    StrKey.buyExtraTitle: 'Extra-Versuch kaufen?',
    StrKey.buyExtraMessage:
        'Gib {n} Münzen aus für einen weiteren erlaubten Fehler in diesem Level.',
    StrKey.buy: 'Kaufen',
    StrKey.encStart: 'Knacken wir dieses Wort!',
    StrKey.encWon: 'Klasse gemacht!',
    StrKey.encLost: 'Fast – versuchen wir es nochmal.',
    StrKey.encAlmost: 'Fast geschafft!',
    StrKey.encNice: 'Gute Wahl!',
    StrKey.encTryAnother: 'Probier einen anderen Buchstaben.',
    StrKey.settingsTitle: 'Einstellungen',
    StrKey.settingSound: 'Soundeffekte',
    StrKey.settingMusic: 'Hintergrundmusik',
    StrKey.settingVibration: 'Vibration',
    StrKey.replayTutorial: 'Tutorial wiederholen',
    StrKey.privacyPolicy: 'Datenschutz',
    StrKey.termsOfUse: 'Nutzungsbedingungen',
    StrKey.privacyChoices: 'Datenschutz-Optionen',
    StrKey.resetProgress: 'Fortschritt zurücksetzen',
    StrKey.settingLanguage: 'Sprache',
    StrKey.resetTitle1: 'Gesamten Fortschritt zurücksetzen?',
    StrKey.resetMsg1:
        'Das löscht Level, Sterne, Münzen, Serien und die Tagesaufgabe.',
    StrKey.resetContinueLabel: 'Weiter',
    StrKey.resetTitle2: 'Bist du ganz sicher?',
    StrKey.resetMsg2:
        'Das kann nicht rückgängig gemacht werden. Ganz neu starten?',
    StrKey.resetConfirmLabel: 'Alles zurücksetzen',
    StrKey.resetDone: 'Fortschritt zurückgesetzt. Neustart!',
    StrKey.skip: 'Überspringen',
    StrKey.startPlaying: 'Los geht’s',
    StrKey.tut1Title: 'Lies den Hinweis',
    StrKey.tut1Body:
        'Jede Runde zeigt eine Frage oder einen Hinweis. Er verrät dir das '
        'gesuchte Wort.',
    StrKey.tut2Title: 'Buchstaben wählen',
    StrKey.tut2Body:
        'Tippe Buchstaben an. Richtige werden grün und füllen die Lücken.',
    StrKey.tut3Title: 'Achte auf Fehler',
    StrKey.tut3Body:
        'Falsche Buchstaben kosten einen Versuch und bringen unseren Freund in '
        'eine lustige Lage. Sind sie alle weg, endet die Runde.',
    StrKey.tut4Title: 'Tipps & Münzen',
    StrKey.tut4Body:
        'Steckst du fest? Gib Münzen für Tipps aus: Buchstaben aufdecken, '
        'falsche entfernen oder einen Extra-Versuch holen.',
    StrKey.tutDemoClue: 'Welches Tier baut Dämme?',
    StrKey.twoPlayerTitle: 'Zwei Spieler',
    StrKey.playerOne: 'Spieler 1',
    StrKey.secretPrompt:
        'Tippe ein Feld an und gib ein geheimes Wort für Spieler 2 ein.',
    StrKey.secretWordLabel: 'Geheimes Wort',
    StrKey.clueOptionalLabel: 'Hinweis (optional)',
    StrKey.secretHint: 'z. B. REGENBOGEN',
    StrKey.clueHint: 'Gib einen netten Hinweis',
    StrKey.allowedMistakes: 'Erlaubte Fehler: {n}',
    StrKey.passToPlayer2: 'An Spieler 2 übergeben',
    StrKey.showWord: 'Wort zeigen',
    StrKey.hideWord: 'Wort verbergen',
    StrKey.valEmpty: 'Bitte gib ein geheimes Wort ein.',
    StrKey.valChars: 'Nur Buchstaben, Leerzeichen und Bindestriche.',
    StrKey.valNeedsLetter: 'Das Wort braucht mindestens einen Buchstaben.',
    StrKey.valMinLen: 'Mindestens {n} Buchstaben, bitte.',
    StrKey.valMaxLen: 'Höchstens {n} Buchstaben.',
    StrKey.twoPlayerClue: 'Errate das geheime Wort von Spieler 1!',
    StrKey.twoPlayerCategory: 'Zwei Spieler',
    StrKey.levelSelectTitle: 'Levelauswahl',
    StrKey.invalidTitle: 'Diese Seite ist vom Papier gerutscht',
    StrKey.invalidBody:
        'Dieses Level ist noch nicht verfügbar. Gehen wir zurück und wählen ein '
        'anderes.',
    StrKey.backToLevels: 'Zurück zu den Leveln',
    StrKey.chooseLanguage: 'Wähle deine Sprache',
    StrKey.chooseLanguageSub: 'Menüs und Rätsel sind dann in dieser Sprache.',
    StrKey.changeLanguageAnytime:
        'Du kannst sie später in den Einstellungen ändern.',
  };

  static const Map<StrKey, String> _sv = {
    StrKey.back: 'Tillbaka',
    StrKey.home: 'Hem',
    StrKey.continueLevel: 'Fortsätt • Nivå {n}',
    StrKey.levelSelect: 'Välj nivå',
    StrKey.twoPlayer: 'Två spelare',
    StrKey.dailyChallenge: 'Dagens utmaning',
    StrKey.levelsProgress: '{done} / {total} nivåer',
    StrKey.freeCoins: 'Gratis {n} mynt',
    StrKey.loadingAd: 'Annons laddas…',
    StrKey.greatJob: 'Bra jobbat!',
    StrKey.outOfChances: 'Slut på chanser!',
    StrKey.lossEncourage: 'Ingen fara – varje gissning gör dig vassare.',
    StrKey.theAnswerWas: 'Svaret var',
    StrKey.statCoins: 'Mynt',
    StrKey.statAccuracy: 'Träffsäkerhet',
    StrKey.statMistakes: 'Fel',
    StrKey.statStreak: 'Svit',
    StrKey.statDailyStreak: 'Dagssvit',
    StrKey.rewardChest: 'Skattkista',
    StrKey.openChest: 'Öppna kistan!',
    StrKey.chestReward: '+{n} från kistan!',
    StrKey.replay: 'Spela igen',
    StrKey.next: 'Nästa',
    StrKey.tryAgain: 'Försök igen',
    StrKey.newRound: 'Ny runda',
    StrKey.backToHome: 'Till hem',
    StrKey.levelTitle: 'Nivå {n}',
    StrKey.dailyTitle: 'Dagens utmaning',
    StrKey.playerTwoTurn: 'Spelare 2:s tur',
    StrKey.hintReveal: 'Avslöja',
    StrKey.hintClear: 'Ta {n}',
    StrKey.hintPlusLife: '+1 Liv',
    StrKey.notEnoughCoins: 'Inte tillräckligt med mynt för det tipset.',
    StrKey.noLettersHint: 'Inga bokstäver kvar för det tipset.',
    StrKey.alreadyExtra: 'Du har redan använt en extra chans här.',
    StrKey.revealWatchAd: 'Avslöja en bokstav – se annons',
    StrKey.reviveTitle: 'Slut på chanser!',
    StrKey.reviveMessage:
        'Se en kort annons för {n} fler gissningar och fortsätt nivån?',
    StrKey.watchAd: 'Se annons',
    StrKey.noThanks: 'Nej tack',
    StrKey.leaveTitle: 'Lämna nivån?',
    StrKey.leaveMessage: 'Dina framsteg på det här ordet försvinner.',
    StrKey.leave: 'Lämna',
    StrKey.stay: 'Stanna',
    StrKey.noAdAvailable: 'Ingen annons tillgänglig just nu.',
    StrKey.buyExtraTitle: 'Köpa en extra chans?',
    StrKey.buyExtraMessage:
        'Spendera {n} mynt för ett fel till på den här nivån.',
    StrKey.buy: 'Köp',
    StrKey.encStart: 'Nu knäcker vi ordet!',
    StrKey.encWon: 'Lysande jobbat!',
    StrKey.encLost: 'Så nära – vi försöker igen.',
    StrKey.encAlmost: 'Snart där!',
    StrKey.encNice: 'Bra val!',
    StrKey.encTryAnother: 'Prova en annan bokstav.',
    StrKey.settingsTitle: 'Inställningar',
    StrKey.settingSound: 'Ljudeffekter',
    StrKey.settingMusic: 'Bakgrundsmusik',
    StrKey.settingVibration: 'Vibration',
    StrKey.replayTutorial: 'Spela guiden igen',
    StrKey.privacyPolicy: 'Integritetspolicy',
    StrKey.termsOfUse: 'Användarvillkor',
    StrKey.privacyChoices: 'Integritetsval',
    StrKey.resetProgress: 'Nollställ framsteg',
    StrKey.settingLanguage: 'Språk',
    StrKey.resetTitle1: 'Nollställa alla framsteg?',
    StrKey.resetMsg1:
        'Det rensar nivåer, stjärnor, mynt, svit och dagens utmaning.',
    StrKey.resetContinueLabel: 'Fortsätt',
    StrKey.resetTitle2: 'Är du helt säker?',
    StrKey.resetMsg2: 'Det går inte att ångra. Börja helt om?',
    StrKey.resetConfirmLabel: 'Nollställ allt',
    StrKey.resetDone: 'Framsteg nollställda. Ny start!',
    StrKey.skip: 'Hoppa över',
    StrKey.startPlaying: 'Börja spela',
    StrKey.tut1Title: 'Läs ledtråden',
    StrKey.tut1Body:
        'Varje runda visar en fråga eller ledtråd. Den säger vilket ord du ska '
        'hitta.',
    StrKey.tut2Title: 'Välj bokstäver',
    StrKey.tut2Body:
        'Tryck på bokstäver för att gissa. Rätt bokstäver blir gröna och fyller '
        'luckorna.',
    StrKey.tut3Title: 'Se upp för fel',
    StrKey.tut3Body:
        'Fel bokstäver kostar en chans och sätter vår figur i en lustig knipa. '
        'Tar de slut är rundan över.',
    StrKey.tut4Title: 'Tips & mynt',
    StrKey.tut4Body:
        'Fast? Spendera mynt på tips: avslöja en bokstav, ta bort fel eller få '
        'en extra chans.',
    StrKey.tutDemoClue: 'Vilket djur bygger dammar?',
    StrKey.twoPlayerTitle: 'Två spelare',
    StrKey.playerOne: 'Spelare 1',
    StrKey.secretPrompt:
        'Tryck på en ruta och skriv ett hemligt ord åt spelare 2.',
    StrKey.secretWordLabel: 'Hemligt ord',
    StrKey.clueOptionalLabel: 'Ledtråd (valfritt)',
    StrKey.secretHint: 't.ex. REGNBÅGE',
    StrKey.clueHint: 'Ge en snäll ledtråd',
    StrKey.allowedMistakes: 'Tillåtna fel: {n}',
    StrKey.passToPlayer2: 'Lämna till spelare 2',
    StrKey.showWord: 'Visa ord',
    StrKey.hideWord: 'Dölj ord',
    StrKey.valEmpty: 'Ange ett hemligt ord.',
    StrKey.valChars: 'Endast bokstäver, mellanslag och bindestreck.',
    StrKey.valNeedsLetter: 'Ordet behöver minst en bokstav.',
    StrKey.valMinLen: 'Gör det minst {n} bokstäver.',
    StrKey.valMaxLen: 'Håll det under {n} bokstäver.',
    StrKey.twoPlayerClue: 'Gissa spelare 1:s hemliga ord!',
    StrKey.twoPlayerCategory: 'Två spelare',
    StrKey.levelSelectTitle: 'Välj nivå',
    StrKey.invalidTitle: 'Den sidan rann av pappret',
    StrKey.invalidBody:
        'Den här nivån är inte tillgänglig än. Vi går tillbaka och väljer en '
        'annan.',
    StrKey.backToLevels: 'Tillbaka till nivåer',
    StrKey.chooseLanguage: 'Välj ditt språk',
    StrKey.chooseLanguageSub: 'Menyer och pussel blir på det här språket.',
    StrKey.changeLanguageAnytime: 'Du kan ändra det senare i inställningarna.',
  };

  static const Map<StrKey, String> _fi = {
    StrKey.back: 'Takaisin',
    StrKey.home: 'Koti',
    StrKey.continueLevel: 'Jatka • Taso {n}',
    StrKey.levelSelect: 'Valitse taso',
    StrKey.twoPlayer: 'Kaksi pelaajaa',
    StrKey.dailyChallenge: 'Päivän haaste',
    StrKey.levelsProgress: '{done} / {total} tasoa',
    StrKey.freeCoins: 'Ilmaiset {n} kolikkoa',
    StrKey.loadingAd: 'Mainos latautuu…',
    StrKey.greatJob: 'Hienoa työtä!',
    StrKey.outOfChances: 'Yritykset loppuivat!',
    StrKey.lossEncourage:
        'Ei hätää – jokainen arvaus tekee sinusta terävämmän.',
    StrKey.theAnswerWas: 'Vastaus oli',
    StrKey.statCoins: 'Kolikot',
    StrKey.statAccuracy: 'Tarkkuus',
    StrKey.statMistakes: 'Virheet',
    StrKey.statStreak: 'Putki',
    StrKey.statDailyStreak: 'Päiväputki',
    StrKey.rewardChest: 'Aarrearkku',
    StrKey.openChest: 'Avaa arkku!',
    StrKey.chestReward: '+{n} arkusta!',
    StrKey.replay: 'Pelaa uudelleen',
    StrKey.next: 'Seuraava',
    StrKey.tryAgain: 'Yritä uudelleen',
    StrKey.newRound: 'Uusi kierros',
    StrKey.backToHome: 'Kotiin',
    StrKey.levelTitle: 'Taso {n}',
    StrKey.dailyTitle: 'Päivän haaste',
    StrKey.playerTwoTurn: 'Pelaajan 2 vuoro',
    StrKey.hintReveal: 'Paljasta',
    StrKey.hintClear: 'Poista {n}',
    StrKey.hintPlusLife: '+1 elämä',
    StrKey.notEnoughCoins: 'Ei tarpeeksi kolikoita tähän vihjeeseen.',
    StrKey.noLettersHint: 'Ei kirjaimia jäljellä tähän vihjeeseen.',
    StrKey.alreadyExtra: 'Käytit jo lisäyrityksen tässä.',
    StrKey.revealWatchAd: 'Paljasta kirjain – katso mainos',
    StrKey.reviveTitle: 'Yritykset loppuivat!',
    StrKey.reviveMessage:
        'Katso lyhyt mainos ja saat {n} lisäarvausta tähän tasoon?',
    StrKey.watchAd: 'Katso mainos',
    StrKey.noThanks: 'Ei kiitos',
    StrKey.leaveTitle: 'Poistutaanko tasosta?',
    StrKey.leaveMessage: 'Edistymisesi tässä sanassa katoaa.',
    StrKey.leave: 'Poistu',
    StrKey.stay: 'Jää',
    StrKey.noAdAvailable: 'Ei mainosta juuri nyt.',
    StrKey.buyExtraTitle: 'Ostetaanko lisäyritys?',
    StrKey.buyExtraMessage:
        'Käytä {n} kolikkoa yhteen lisävirheeseen tässä tasossa.',
    StrKey.buy: 'Osta',
    StrKey.encStart: 'Ratkotaan tämä sana!',
    StrKey.encWon: 'Loistavaa työtä!',
    StrKey.encLost: 'Lähellä – yritetään uudelleen.',
    StrKey.encAlmost: 'Melkein perillä!',
    StrKey.encNice: 'Hyvä valinta!',
    StrKey.encTryAnother: 'Kokeile toista kirjainta.',
    StrKey.settingsTitle: 'Asetukset',
    StrKey.settingSound: 'Ääniefektit',
    StrKey.settingMusic: 'Taustamusiikki',
    StrKey.settingVibration: 'Värinä',
    StrKey.replayTutorial: 'Toista opastus',
    StrKey.privacyPolicy: 'Tietosuojakäytäntö',
    StrKey.termsOfUse: 'Käyttöehdot',
    StrKey.privacyChoices: 'Tietosuoja-asetukset',
    StrKey.resetProgress: 'Nollaa edistyminen',
    StrKey.settingLanguage: 'Kieli',
    StrKey.resetTitle1: 'Nollataanko kaikki edistyminen?',
    StrKey.resetMsg1:
        'Tämä poistaa tasot, tähdet, kolikot, putket ja päivän haasteen.',
    StrKey.resetContinueLabel: 'Jatka',
    StrKey.resetTitle2: 'Oletko aivan varma?',
    StrKey.resetMsg2: 'Tätä ei voi perua. Aloitetaanko täysin alusta?',
    StrKey.resetConfirmLabel: 'Nollaa kaikki',
    StrKey.resetDone: 'Edistyminen nollattu. Uusi alku!',
    StrKey.skip: 'Ohita',
    StrKey.startPlaying: 'Aloita peli',
    StrKey.tut1Title: 'Lue vihje',
    StrKey.tut1Body:
        'Joka kierros näyttää kysymyksen tai vihjeen. Se kertoo, mikä sana '
        'etsitään.',
    StrKey.tut2Title: 'Valitse kirjaimia',
    StrKey.tut2Body:
        'Napauta kirjaimia arvataksesi. Oikeat muuttuvat vihreiksi ja täyttävät '
        'aukot.',
    StrKey.tut3Title: 'Varo virheitä',
    StrKey.tut3Body:
        'Väärät kirjaimet maksavat yrityksen ja vievät hahmomme hassuun pulaan. '
        'Kun ne loppuvat, kierros päättyy.',
    StrKey.tut4Title: 'Vihjeet & kolikot',
    StrKey.tut4Body:
        'Jäitkö jumiin? Käytä kolikoita vihjeisiin: paljasta kirjain, poista '
        'vääriä tai osta lisäyritys.',
    StrKey.tutDemoClue: 'Mikä eläin rakentaa patoja?',
    StrKey.twoPlayerTitle: 'Kaksi pelaajaa',
    StrKey.playerOne: 'Pelaaja 1',
    StrKey.secretPrompt:
        'Napauta ruutua ja kirjoita salainen sana pelaajalle 2.',
    StrKey.secretWordLabel: 'Salainen sana',
    StrKey.clueOptionalLabel: 'Vihje (valinnainen)',
    StrKey.secretHint: 'esim. SATEENKAARI',
    StrKey.clueHint: 'Anna ystävällinen vihje',
    StrKey.allowedMistakes: 'Sallitut virheet: {n}',
    StrKey.passToPlayer2: 'Anna pelaajalle 2',
    StrKey.showWord: 'Näytä sana',
    StrKey.hideWord: 'Piilota sana',
    StrKey.valEmpty: 'Anna salainen sana.',
    StrKey.valChars: 'Vain kirjaimia, välilyöntejä ja väliviivoja.',
    StrKey.valNeedsLetter: 'Sanassa on oltava vähintään yksi kirjain.',
    StrKey.valMinLen: 'Vähintään {n} kirjainta.',
    StrKey.valMaxLen: 'Enintään {n} kirjainta.',
    StrKey.twoPlayerClue: 'Arvaa pelaajan 1 salainen sana!',
    StrKey.twoPlayerCategory: 'Kaksi pelaajaa',
    StrKey.levelSelectTitle: 'Valitse taso',
    StrKey.invalidTitle: 'Se sivu karkasi paperilta',
    StrKey.invalidBody:
        'Tämä taso ei ole vielä käytettävissä. Palataan ja valitaan toinen.',
    StrKey.backToLevels: 'Takaisin tasoihin',
    StrKey.chooseLanguage: 'Valitse kielesi',
    StrKey.chooseLanguageSub: 'Valikot ja pulmat ovat tällä kielellä.',
    StrKey.changeLanguageAnytime: 'Voit vaihtaa sen myöhemmin asetuksista.',
  };
}
